print('_=-' * 20)
valor = float(input('Digite um valor em METROS: '))
print('_=-' * 20)
print('O valor de {:.0f} metros convertido em km é: '.format(valor), (valor * 0.001), 'Km')
print('O valor de {:.0f} metros convertido em hm é: '.format(valor), (valor * 0.01), 'hm')
print('O valor de {:.0f} metros convertido em dam é: '.format(valor), (valor * 0.1), 'dam')
print('O valor de {:.0f} metros convertido em dm é: '.format(valor), (valor * 10), 'dm')
print('O valor de {:.0f} metros convertido em cm é: '.format(valor), (valor * 100), 'cm')
print('O valor de {:.0f} metros convertido em mm é: '.format(valor), (valor * 1000), 'mm')
